apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: code-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
