apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: droneci
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
