apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: duckdns
  name: duckdns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: duckdns
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: duckdns
    spec:
      containers:
      - image: ghcr.io/linuxserver/duckdns
        name: duckdns
        envFrom:
        - configMapRef:
            name: duckdns-cm
        resources: {}
status: {}
