apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rxresume-db
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: longhorn-static
  volumeMode: Filesystem
  volumeName: rxresume-db

