apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: guacamole
  name: guacamole-client-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 512Mi
