apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-static
  volumeMode: Filesystem
  volumeName: gitea