apiVersion: v1
kind: Secret
metadata:
  namespace: droneci
  name: drone-server-secret
type: Opaque
data: 
  DRONE_DATABASE_DATASOURCE: cG9zdGdyZXM6Ly9wb3N0Z3Jlc2FkbWluOmFkbWluMTIzQHBvc3RncmVzOjU0MzIvcG9zdGdyZXNkYj9zc2xtb2RlPWRpc2FibGU=
  DRONE_GITHUB_CLIENT_ID: OTU3MWQzMmNiNWUzYmI3ZDAzZmE=
  DRONE_GITHUB_CLIENT_SECRET: ZDBjMDMyMjliZGE5ZGE4ZGVjZTU2ZTBhMzMyZDMzYWRhNmYxNmYwYQ==
  DRONE_RPC_SECRET: Njg4YmQ3NWU2Zjg2OTFiYTJjYmYwNDBlY2VhMjc1ZGM=
  DRONE_SERVER_HOST: ZHJvbmUucGF6b24ud29yaw==
  DRONE_USER_CREATE: dXNlcm5hbWU6YWRtaW4sYWRtaW46dHJ1ZQ==