apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2023-08-26T10:36:38Z"
  generation: 11
  managedFields:
  - apiVersion: argoproj.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:destination:
          .: {}
          f:namespace: {}
          f:server: {}
        f:project: {}
        f:source:
          .: {}
          f:directory:
            .: {}
            f:include: {}
            f:jsonnet: {}
            f:recurse: {}
          f:path: {}
          f:repoURL: {}
          f:targetRevision: {}
        f:syncPolicy:
          .: {}
          f:automated: {}
      f:status:
        .: {}
        f:health: {}
        f:summary: {}
        f:sync:
          .: {}
          f:comparedTo:
            .: {}
            f:destination: {}
            f:source: {}
    manager: argocd-server
    operation: Update
    time: "2023-08-26T10:36:38Z"
  - apiVersion: argoproj.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:controllerNamespace: {}
        f:health:
          f:status: {}
        f:history: {}
        f:operationState:
          .: {}
          f:finishedAt: {}
          f:message: {}
          f:operation:
            .: {}
            f:initiatedBy:
              .: {}
              f:automated: {}
            f:retry:
              .: {}
              f:limit: {}
            f:sync:
              .: {}
              f:revision: {}
          f:phase: {}
          f:startedAt: {}
          f:syncResult:
            .: {}
            f:resources: {}
            f:revision: {}
            f:source:
              .: {}
              f:directory:
                .: {}
                f:include: {}
                f:jsonnet: {}
                f:recurse: {}
              f:path: {}
              f:repoURL: {}
              f:targetRevision: {}
        f:reconciledAt: {}
        f:resources: {}
        f:sourceType: {}
        f:summary:
          f:externalURLs: {}
          f:images: {}
        f:sync:
          f:comparedTo:
            f:destination:
              f:namespace: {}
              f:server: {}
            f:source:
              f:directory:
                .: {}
                f:include: {}
                f:jsonnet: {}
                f:recurse: {}
              f:path: {}
              f:repoURL: {}
              f:targetRevision: {}
          f:revision: {}
          f:status: {}
    manager: argocd-application-controller
    operation: Update
    time: "2023-08-26T10:36:40Z"
  name: code-server
  namespace: argocd
  resourceVersion: "1804593"
  uid: e0291a74-8eae-4b22-86cb-2f063342bef6
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      include: '*.yaml'
      jsonnet: {}
      recurse: true
    path: code-server
    repoURL: https://github.com/jogaleins/examples.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
status:
  controllerNamespace: argocd
  health:
    status: Healthy
  history:
  - deployStartedAt: "2023-08-26T10:36:39Z"
    deployedAt: "2023-08-26T10:36:40Z"
    id: 0
    revision: c8d2b9c04ba4ab71516dfbaff2d37317ad3d9b09
    source:
      directory:
        include: '*.yaml'
        jsonnet: {}
        recurse: true
      path: code-server
      repoURL: https://github.com/jogaleins/examples.git
      targetRevision: HEAD
  operationState:
    finishedAt: "2023-08-26T10:36:40Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        automated: true
      retry:
        limit: 5
      sync:
        revision: c8d2b9c04ba4ab71516dfbaff2d37317ad3d9b09
    phase: Succeeded
    startedAt: "2023-08-26T10:36:39Z"
    syncResult:
      resources:
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/code-server configured
        name: code-server
        namespace: default
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        kind: Deployment
        message: deployment.apps/code-server configured
        name: code-server
        namespace: default
        status: Synced
        syncPhase: Sync
        version: v1
      - group: networking.k8s.io
        hookPhase: Running
        kind: Ingress
        message: ingress.networking.k8s.io/code-server configured
        name: code-server
        namespace: default
        status: Synced
        syncPhase: Sync
        version: v1
      revision: c8d2b9c04ba4ab71516dfbaff2d37317ad3d9b09
      source:
        directory:
          include: '*.yaml'
          jsonnet: {}
          recurse: true
        path: code-server
        repoURL: https://github.com/jogaleins/examples.git
        targetRevision: HEAD
  reconciledAt: "2023-08-26T10:36:40Z"
  resources:
  - health:
      status: Healthy
    kind: Service
    name: code-server
    namespace: default
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: code-server
    namespace: default
    status: Synced
    version: v1
  - group: networking.k8s.io
    health:
      status: Healthy
    kind: Ingress
    name: code-server
    namespace: default
    status: Synced
    version: v1
  sourceType: Directory
  summary:
    externalURLs:
    - http://code.lan.pazon.xyz
    - http://code.pazon.xyz
    images:
    - jogaleins/code-server:latest
  sync:
    comparedTo:
      destination:
        namespace: default
        server: https://kubernetes.default.svc
      source:
        directory:
          include: '*.yaml'
          jsonnet: {}
          recurse: true
        path: code-server
        repoURL: https://github.com/jogaleins/examples.git
        targetRevision: HEAD
    revision: c8d2b9c04ba4ab71516dfbaff2d37317ad3d9b09
    status: Synced
