apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"Application","metadata":{"annotations":{},"creationTimestamp":"2023-05-24T02:13:27Z","generation":9,"name":"guacamole","namespace":"argocd","resourceVersion":"133629","uid":"66b842a6-8ae7-4edd-ae82-b62062e98987"},"spec":{"destination":{"namespace":"guacamole","server":"https://kubernetes.default.svc"},"project":"default","source":{"directory":{"include":"*.yaml","jsonnet":{}},"path":"guacamole","repoURL":"https://github.com/jogaleins/examples.git","targetRevision":"HEAD"},"syncPolicy":{"automated":{}}},"status":{"health":{"status":"Healthy"},"history":[{"deployStartedAt":"2023-05-24T02:13:29Z","deployedAt":"2023-05-24T02:13:30Z","id":0,"revision":"2fc189cdec3cc3e8f6a74f8558869c917e334366","source":{"directory":{"include":"*.yaml","jsonnet":{}},"path":"guacamole","repoURL":"https://github.com/jogaleins/examples.git","targetRevision":"HEAD"}}],"operationState":{"finishedAt":"2023-05-24T02:13:30Z","message":"successfully synced (all tasks run)","operation":{"initiatedBy":{"automated":true},"retry":{"limit":5},"sync":{"revision":"2fc189cdec3cc3e8f6a74f8558869c917e334366"}},"phase":"Succeeded","startedAt":"2023-05-24T02:13:29Z","syncResult":{"resources":[{"group":"","hookPhase":"Running","kind":"Namespace","message":"namespace/guacamole configured","name":"guacamole","namespace":"guacamole","status":"Synced","syncPhase":"Sync","version":"v1"},{"group":"","hookPhase":"Running","kind":"Secret","message":"secret/postgres-secret configured","name":"postgres-secret","namespace":"guacamole","status":"Synced","syncPhase":"Sync","version":"v1"},{"group":"","hookPhase":"Running","kind":"PersistentVolumeClaim","message":"persistentvolumeclaim/guacd-pvc configured","name":"guacd-pvc","namespace":"guacamole","status":"Synced","syncPhase":"Sync","version":"v1"},{"group":"","hookPhase":"Running","kind":"PersistentVolumeClaim","message":"persistentvolumeclaim/guacamole-client-pvc configured","name":"guacamole-client-pvc","namespace":"guacamole","status":"Synced","syncPhase":"Sync","version":"v1"},{"group":"","hookPhase":"Running","kind":"PersistentVolumeClaim","message":"persistentvolumeclaim/guacamole-db-pvc configured","name":"guacamole-db-pvc","namespace":"guacamole","status":"Synced","syncPhase":"Sync","version":"v1"},{"group":"","hookPhase":"Running","kind":"Service","message":"service/guacamole configured","name":"guacamole","namespace":"guacamole","status":"Synced","syncPhase":"Sync","version":"v1"},{"group":"","hookPhase":"Running","kind":"Service","message":"service/guacd configured","name":"guacd","namespace":"guacamole","status":"Synced","syncPhase":"Sync","version":"v1"},{"group":"","hookPhase":"Running","kind":"Service","message":"service/postgres configured","name":"postgres","namespace":"guacamole","status":"Synced","syncPhase":"Sync","version":"v1"},{"group":"apps","hookPhase":"Running","kind":"Deployment","message":"deployment.apps/guacamole configured","name":"guacamole","namespace":"guacamole","status":"Synced","syncPhase":"Sync","version":"v1"},{"group":"apps","hookPhase":"Running","kind":"Deployment","message":"deployment.apps/guacd configured","name":"guacd","namespace":"guacamole","status":"Synced","syncPhase":"Sync","version":"v1"},{"group":"apps","hookPhase":"Running","kind":"Deployment","message":"deployment.apps/postgres configured","name":"postgres","namespace":"guacamole","status":"Synced","syncPhase":"Sync","version":"v1"},{"group":"networking.k8s.io","hookPhase":"Running","kind":"Ingress","message":"ingress.networking.k8s.io/guacamole configured","name":"guacamole","namespace":"guacamole","status":"Synced","syncPhase":"Sync","version":"v1"}],"revision":"2fc189cdec3cc3e8f6a74f8558869c917e334366","source":{"directory":{"include":"*.yaml","jsonnet":{}},"path":"guacamole","repoURL":"https://github.com/jogaleins/examples.git","targetRevision":"HEAD"}}},"reconciledAt":"2023-05-24T02:13:30Z","resources":[{"kind":"Namespace","name":"guacamole","status":"Synced","version":"v1"},{"health":{"status":"Healthy"},"kind":"PersistentVolumeClaim","name":"guacamole-client-pvc","namespace":"guacamole","status":"Synced","version":"v1"},{"health":{"status":"Healthy"},"kind":"PersistentVolumeClaim","name":"guacamole-db-pvc","namespace":"guacamole","status":"Synced","version":"v1"},{"health":{"status":"Healthy"},"kind":"PersistentVolumeClaim","name":"guacd-pvc","namespace":"guacamole","status":"Synced","version":"v1"},{"kind":"Secret","name":"postgres-secret","namespace":"guacamole","status":"Synced","version":"v1"},{"health":{"status":"Healthy"},"kind":"Service","name":"guacamole","namespace":"guacamole","status":"Synced","version":"v1"},{"health":{"status":"Healthy"},"kind":"Service","name":"guacd","namespace":"guacamole","status":"Synced","version":"v1"},{"health":{"status":"Healthy"},"kind":"Service","name":"postgres","namespace":"guacamole","status":"Synced","version":"v1"},{"group":"apps","health":{"status":"Healthy"},"kind":"Deployment","name":"guacamole","namespace":"guacamole","status":"Synced","version":"v1"},{"group":"apps","health":{"status":"Healthy"},"kind":"Deployment","name":"guacd","namespace":"guacamole","status":"Synced","version":"v1"},{"group":"apps","health":{"status":"Healthy"},"kind":"Deployment","name":"postgres","namespace":"guacamole","status":"Synced","version":"v1"},{"group":"networking.k8s.io","health":{"status":"Healthy"},"kind":"Ingress","name":"guacamole","namespace":"guacamole","status":"Synced","version":"v1"}],"sourceType":"Directory","summary":{"externalURLs":["http://guacamole.pazon.work/"],"images":["jwetzell/guacamole","linuxserver/guacd:latest","postgres:13.4"]},"sync":{"comparedTo":{"destination":{"namespace":"guacamole","server":"https://kubernetes.default.svc"},"source":{"directory":{"include":"*.yaml","jsonnet":{}},"path":"guacamole","repoURL":"https://github.com/jogaleins/examples.git","targetRevision":"HEAD"}},"revision":"2fc189cdec3cc3e8f6a74f8558869c917e334366","status":"Synced"}}}
  creationTimestamp: "2023-08-23T11:52:58Z"
  generation: 1514
  managedFields:
  - apiVersion: argoproj.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        .: {}
        f:destination:
          .: {}
          f:namespace: {}
          f:server: {}
        f:project: {}
        f:source:
          .: {}
          f:directory:
            .: {}
            f:include: {}
            f:jsonnet: {}
          f:path: {}
          f:repoURL: {}
          f:targetRevision: {}
        f:syncPolicy:
          .: {}
          f:automated: {}
      f:status:
        .: {}
        f:health: {}
        f:summary: {}
        f:sync:
          .: {}
          f:comparedTo:
            .: {}
            f:destination:
              .: {}
              f:namespace: {}
              f:server: {}
            f:source:
              .: {}
              f:directory:
                .: {}
                f:include: {}
                f:jsonnet: {}
              f:path: {}
              f:repoURL: {}
              f:targetRevision: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2023-08-23T11:52:58Z"
  - apiVersion: argoproj.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:controllerNamespace: {}
        f:health:
          f:status: {}
        f:history: {}
        f:operationState:
          .: {}
          f:finishedAt: {}
          f:message: {}
          f:operation:
            .: {}
            f:initiatedBy:
              .: {}
              f:username: {}
            f:retry: {}
            f:sync:
              .: {}
              f:revision: {}
              f:syncStrategy:
                .: {}
                f:hook: {}
          f:phase: {}
          f:startedAt: {}
          f:syncResult:
            .: {}
            f:resources: {}
            f:revision: {}
            f:source:
              .: {}
              f:directory:
                .: {}
                f:include: {}
                f:jsonnet: {}
              f:path: {}
              f:repoURL: {}
              f:targetRevision: {}
        f:reconciledAt: {}
        f:resources: {}
        f:sourceType: {}
        f:summary:
          f:externalURLs: {}
          f:images: {}
        f:sync:
          f:revision: {}
          f:status: {}
    manager: argocd-application-controller
    operation: Update
    time: "2023-08-26T09:15:58Z"
  name: guacamole
  namespace: argocd
  resourceVersion: "1760485"
  uid: cad2c486-6d36-4bf0-8b71-3ba95483bbda
spec:
  destination:
    namespace: guacamole
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      include: '*.yaml'
      jsonnet: {}
    path: guacamole
    repoURL: https://github.com/jogaleins/examples.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
status:
  controllerNamespace: argocd
  health:
    status: Healthy
  history:
  - deployStartedAt: "2023-05-24T02:13:29Z"
    deployedAt: "2023-05-24T02:13:30Z"
    id: 0
    revision: 2fc189cdec3cc3e8f6a74f8558869c917e334366
    source:
      directory:
        include: '*.yaml'
        jsonnet: {}
      path: guacamole
      repoURL: https://github.com/jogaleins/examples.git
      targetRevision: HEAD
  - deployStartedAt: "2023-08-23T11:52:59Z"
    deployedAt: "2023-08-23T11:53:00Z"
    id: 1
    revision: ffd920e9aa9d522327a11c60f60efc753ebfc394
    source:
      directory:
        include: '*.yaml'
        jsonnet: {}
      path: guacamole
      repoURL: https://github.com/jogaleins/examples.git
      targetRevision: HEAD
  - deployStartedAt: "2023-08-25T04:27:24Z"
    deployedAt: "2023-08-25T04:27:25Z"
    id: 2
    revision: 958859d3d24fd6d97000cd159bf45ca8d26b1625
    source:
      directory:
        include: '*.yaml'
        jsonnet: {}
      path: guacamole
      repoURL: https://github.com/jogaleins/examples.git
      targetRevision: HEAD
  operationState:
    finishedAt: "2023-08-25T04:27:25Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        username: admin
      retry: {}
      sync:
        revision: 958859d3d24fd6d97000cd159bf45ca8d26b1625
        syncStrategy:
          hook: {}
    phase: Succeeded
    startedAt: "2023-08-25T04:27:24Z"
    syncResult:
      resources:
      - group: ""
        hookPhase: Running
        kind: Namespace
        message: namespace/guacamole created
        name: guacamole
        namespace: guacamole
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Secret
        message: secret/postgres-secret created
        name: postgres-secret
        namespace: guacamole
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: PersistentVolumeClaim
        message: persistentvolumeclaim/guacd-pvc created
        name: guacd-pvc
        namespace: guacamole
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: PersistentVolumeClaim
        message: persistentvolumeclaim/guacamole-db-pvc created
        name: guacamole-db-pvc
        namespace: guacamole
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: PersistentVolumeClaim
        message: persistentvolumeclaim/guacamole-client-pvc created
        name: guacamole-client-pvc
        namespace: guacamole
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/postgres created
        name: postgres
        namespace: guacamole
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/guacd created
        name: guacd
        namespace: guacamole
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/guacamole created
        name: guacamole
        namespace: guacamole
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        kind: Deployment
        message: deployment.apps/guacd created
        name: guacd
        namespace: guacamole
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        kind: Deployment
        message: deployment.apps/postgres created
        name: postgres
        namespace: guacamole
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        kind: Deployment
        message: deployment.apps/guacamole created
        name: guacamole
        namespace: guacamole
        status: Synced
        syncPhase: Sync
        version: v1
      - group: networking.k8s.io
        hookPhase: Running
        kind: Ingress
        message: ingress.networking.k8s.io/guacamole created
        name: guacamole
        namespace: guacamole
        status: Synced
        syncPhase: Sync
        version: v1
      revision: 958859d3d24fd6d97000cd159bf45ca8d26b1625
      source:
        directory:
          include: '*.yaml'
          jsonnet: {}
        path: guacamole
        repoURL: https://github.com/jogaleins/examples.git
        targetRevision: HEAD
  reconciledAt: "2023-08-26T09:15:58Z"
  resources:
  - kind: Namespace
    name: guacamole
    status: Synced
    version: v1
  - health:
      status: Healthy
    kind: PersistentVolumeClaim
    name: guacamole-client-pvc
    namespace: guacamole
    status: Synced
    version: v1
  - health:
      status: Healthy
    kind: PersistentVolumeClaim
    name: guacamole-db-pvc
    namespace: guacamole
    status: Synced
    version: v1
  - health:
      status: Healthy
    kind: PersistentVolumeClaim
    name: guacd-pvc
    namespace: guacamole
    status: Synced
    version: v1
  - kind: Secret
    name: postgres-secret
    namespace: guacamole
    status: Synced
    version: v1
  - health:
      status: Healthy
    kind: Service
    name: guacamole
    namespace: guacamole
    status: Synced
    version: v1
  - health:
      status: Healthy
    kind: Service
    name: guacd
    namespace: guacamole
    status: Synced
    version: v1
  - health:
      status: Healthy
    kind: Service
    name: postgres
    namespace: guacamole
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: guacamole
    namespace: guacamole
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: guacd
    namespace: guacamole
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: postgres
    namespace: guacamole
    status: Synced
    version: v1
  - group: networking.k8s.io
    health:
      status: Healthy
    kind: Ingress
    name: guacamole
    namespace: guacamole
    status: Synced
    version: v1
  sourceType: Directory
  summary:
    externalURLs:
    - http://gc.pazon.xyz/
    images:
    - jwetzell/guacamole
    - linuxserver/guacd:latest
    - postgres:13.4
  sync:
    comparedTo:
      destination:
        namespace: guacamole
        server: https://kubernetes.default.svc
      source:
        directory:
          include: '*.yaml'
          jsonnet: {}
        path: guacamole
        repoURL: https://github.com/jogaleins/examples.git
        targetRevision: HEAD
    revision: 0cc92b601b649f9d4cbe9f0f00ffdfd3b6d20d90
    status: Synced
