apiVersion: v1
data:
  credentials.json: eyJBY2NvdW50VGFnIjoiM2IxOWFlM2U4MDJkYjU3ZmJmNTUzZDIzYWZmN2MyNDQiLCJUdW5uZWxTZWNyZXQiOiJnYzhiL1BhOVRtUGVUWWZaY0lnQ2VDM3djMkJkZk5jSEtTRnFERTA1VXdFPSIsIlR1bm5lbElEIjoiYjNkYTNmNzctYWM2OC00M2QzLWJiYzItZGExMDQ1ODMzODI5In0=
kind: Secret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared-argo
