apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ghost
  name: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ghost
    spec:
      containers:
      - image: ghost:5.45.1-alpine
        name: ghost
        env:
        - name: url
          value: http://ghost.pazon.xyz
        - name: database__client
          value: mysql
        - name: database__connection__host
          value: mariadb.default.svc.cluster.local
        - name: database__connection__user
          value: root
        - name: database__connection__password
          value: soeid1
        - name: database__connection__database
          value: bitnami_ghost
        ports:
        - containerPort: 2368
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/ghost/content
          name: content
        resources: {}
      volumes:
      - name: content
        persistentVolumeClaim:
          claimName: ghost-blog-pvc
status: {}
